import { ImageSourcePropType } from 'react-native';

export interface Animal {
  uid: number;
  breed: string;
  animal: string;
  image: ImageSourcePropType;
  url: string; // Public URL for emails
  alt: string;
}

// Base URL for hosted images (update this to your Vercel domain)
const IMAGE_BASE_URL = 'https://sendaboop.app/images/dogs';

export const animals: Animal[] = [
  {
    uid: 0,
    breed: 'golden-retriever',
    animal: 'dog',
    image: require('@/assets/images/animals/jairo-alzate-sssxyuZape8-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/jairo-alzate-sssxyuZape8-unsplash.jpg`,
    alt: 'photographer: Jairo Alzate - Happy golden retriever with tongue out',
  },
  {
    uid: 1,
    breed: 'corgi',
    animal: 'dog',
    image: require('@/assets/images/animals/alvan-nee-NeRrOJJs1J8-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/alvan-nee-NeRrOJJs1J8-unsplash.jpg`,
    alt: 'photographer: Alvan Nee - Adorable corgi looking at camera',
  },
  {
    uid: 2,
    breed: 'pug',
    animal: 'dog',
    image: require('@/assets/images/animals/charlesdeluvio-pOUA8Xay514-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/charlesdeluvio-pOUA8Xay514-unsplash.jpg`,
    alt: 'photographer: Charles Deluvio - Cute pug with head tilted',
  },
  {
    uid: 3,
    breed: 'husky',
    animal: 'dog',
    image: require('@/assets/images/animals/cristina-anne-costello-NR2eMg9zXxA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/cristina-anne-costello-NR2eMg9zXxA-unsplash.jpg`,
    alt: 'photographer: Cristina Anna Costello - Majestic husky with blue eyes',
  },
  {
    uid: 4,
    breed: 'shiba-inu',
    animal: 'dog',
    image: require('@/assets/images/animals/yury-orlov-J16gyd7WtyA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/yury-orlov-J16gyd7WtyA-unsplash.jpg`,
    alt: 'photographer: Yury Orlov - Sweet beagle puppy face',
  },
  {
    uid: 5,
    breed: 'labrador',
    animal: 'dog',
    image: require('@/assets/images/animals/ben-iwara-A2vIKhoRBIM-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/ben-iwara-A2vIKhoRBIM-unsplash.jpg`,
    alt: 'photographer: Ben Iwara - Friendly black labrador',
  },
  {
    uid: 6,
    breed: 'shiba',
    animal: 'dog',
    image: require('@/assets/images/animals/road-ahead-u0H7dup14Bg-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/road-ahead-u0H7dup14Bg-unsplash.jpg`,
    alt: 'photographer: unknown - Smiling shiba inu',
  },
  {
    uid: 7,
    breed: 'dachshund',
    animal: 'dog',
    image: require('@/assets/images/animals/serjan-midili-6jxDHe_RVOA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/serjan-midili-6jxDHe_RVOA-unsplash.jpg`,
    alt: 'photographer: Serjan Midili - Cute dachshund close-up',
  },
  {
    uid: 8,
    breed: 'poodle',
    animal: 'dog',
    image: require('@/assets/images/animals/alsu-vershinina-4gRgy5rjFLI-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/alsu-vershinina-4gRgy5rjFLI-unsplash.jpg`,
    alt: 'photographer: Alsu Vershinina - Fluffy white poodle',
  },
  {
    uid: 9,
    breed: 'bulldog',
    animal: 'dog',
    image: require('@/assets/images/animals/karsten-winegeart-NE0XGVKTmcA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/karsten-winegeart-NE0XGVKTmcA-unsplash.jpg`,
    alt: 'photographer: Karsten Winegart - French bulldog looking adorable',
  },
  {
    uid: 10,
    breed: 'samoyed',
    animal: 'dog',
    image: require('@/assets/images/animals/sarah-b-riZjFy__tlg-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/sarah-b-riZjFy__tlg-unsplash.jpg`,
    alt: 'photographer: Sarah B - Fluffy white samoyed smiling',
  },
  {
    uid: 11,
    breed: 'border-collie',
    animal: 'dog',
    image: require('@/assets/images/animals/jamie-street-jOKje-UpK3k-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/jamie-street-jOKje-UpK3k-unsplash.jpg`,
    alt: 'photographer: Jamie Street - Attentive border collie',
  },
  {
    uid: 12,
    breed: 'chihuahua',
    animal: 'dog',
    image: require('@/assets/images/animals/david-vives-5j4bu68ltyk-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/david-vives-5j4bu68ltyk-unsplash.jpg`,
    alt: 'photographer: David Vives - Tiny chihuahua with big eyes',
  },
  {
    uid: 13,
    breed: 'german-shepherd',
    animal: 'dog',
    image: require('@/assets/images/animals/gursimrat-ganda-zTV6vME0ijk-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/gursimrat-ganda-zTV6vME0ijk-unsplash.jpg`,
    alt: 'photographer: Gursimrat Ganda - Noble german shepherd',
  },
  {
    uid: 14,
    breed: 'maltese',
    animal: 'dog',
    image: require('@/assets/images/animals/danique-veldhuis-brYiSKZ0I_k-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/danique-veldhuis-brYiSKZ0I_k-unsplash.jpg`,
    alt: 'photographer: Danique Veldhuis - Fluffy white maltese',
  },
  {
    uid: 15,
    breed: 'terrier',
    animal: 'dog',
    image: require('@/assets/images/animals/luis-olmos-XwaqPYvYimA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/luis-olmos-XwaqPYvYimA-unsplash.jpg`,
    alt: 'photographer: Luis Olmos - Playful terrier',
  },
  {
    uid: 16,
    breed: 'pitbull',
    animal: 'dog',
    image: require('@/assets/images/animals/michal-mikulec-hr3ckRbpVQQ-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/michal-mikulec-hr3ckRbpVQQ-unsplash.jpg`,
    alt: 'photographer: Michal Mikulec - Sweet pitbull face',
  },
  {
    uid: 17,
    breed: 'aussie',
    animal: 'dog',
    image: require('@/assets/images/animals/michelle-tresemer-r2o_0cIm-GY-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/michelle-tresemer-r2o_0cIm-GY-unsplash.jpg`,
    alt: 'photographer: Michelle Tresemer - Australian shepherd',
  },
  {
    uid: 18,
    breed: 'boxer',
    animal: 'dog',
    image: require('@/assets/images/animals/octavian-horn-pdZmu7pFcNA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/octavian-horn-pdZmu7pFcNA-unsplash.jpg`,
    alt: 'photographer: Octavian Horn - Friendly boxer',
  },
  {
    uid: 19,
    breed: 'bichon',
    animal: 'dog',
    image: require('@/assets/images/animals/rafael-ishkhanyan-sHeEBiExteM-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/rafael-ishkhanyan-sHeEBiExteM-unsplash.jpg`,
    alt: 'photographer: Rafael Ishkhanyan - Fluffy bichon frise',
  },
  {
    uid: 20,
    breed: 'havanese',
    animal: 'dog',
    image: require('@/assets/images/animals/sebin-lalu-cLvJgLR8qnA-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/sebin-lalu-cLvJgLR8qnA-unsplash.jpg`,
    alt: 'photographer: Sebin Lalu - Cute havanese',
  },
  {
    uid: 21,
    breed: 'spaniel',
    animal: 'dog',
    image: require('@/assets/images/animals/anthony-persegol-6AC9sde3n-E-unsplash.jpg'),
    url: `${IMAGE_BASE_URL}/anthony-persegol-6AC9sde3n-E-unsplash.jpg`,
    alt: 'photographer: Anthony Persegol - Cocker spaniel',
  },
  {
    uid: 22,
    breed: 'siamese',
    animal: 'cat',
    image: require('@/assets/images/animals/alex-meier-KGiQFgF7dkc-unsplash.png'),
    url: `${IMAGE_BASE_URL}/alex-meier-KGiQFgF7dkc-unsplash.png`,
    alt: 'photographer: Alex Meier',
  },
    {
    uid: 23,
    breed: 'siberian',
    animal: 'cat',
    image: require('@/assets/images/animals/alvan-nee-ZCHj_2lJP00-unsplash.png'),
    url: `${IMAGE_BASE_URL}/alvan-nee-ZCHj_2lJP00-unsplash.png`,
    alt: 'photographer: Alvan Nee',
  },
    {
    uid: 24,
    breed: 'manx',
    animal: 'cat',
    image: require('@/assets/images/animals/bogdan-farca-CEx86maLUSc-unsplash.png'),
    url: `${IMAGE_BASE_URL}/bogdan-farca-CEx86maLUSc-unsplash.png`,
    alt: 'photographer: Bogdan Farca',
  },
    {
    uid: 25,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/borna-bevanda-VwqecUsYKvs-unsplash.png'),
    url: `${IMAGE_BASE_URL}/borna-bevanda-VwqecUsYKvs-unsplash.png`,
    alt: 'photographer: Borna Bevanda',
  },
    {
    uid: 26,
    breed: 'orange cat',
    animal: 'cat',
    image: require('@/assets/images/animals/daria-averina-_867Jy8LCkI-unsplash.png'),
    url: `${IMAGE_BASE_URL}/daria-averina-_867Jy8LCkI-unsplash.png`,
    alt: 'photographer: Daria Averina',
  },
    {
    uid: 27,
    breed: 'toyger',
    animal: 'cat',
    image: require('@/assets/images/animals/eric-han-WJ6fmN1D-h0-unsplash.png'),
    url: `${IMAGE_BASE_URL}/eric-han-WJ6fmN1D-h0-unsplash.png`,
    alt: 'photographer: Eric Han',
  },
    {
    uid: 28,
    breed: 'turkish-angora',
    animal: 'cat',
    image: require('@/assets/images/animals/kanashi-BLW_KQ0Rkn0-unsplash.png'),
    url: `${IMAGE_BASE_URL}/kanashi-BLW_KQ0Rkn0-unsplash.png`,
    alt: 'photographer: Kanashi',
  },
    {
    uid: 29,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/loan-7AIDE8PrvA0-unsplash.png'),
    url: `${IMAGE_BASE_URL}/loan-7AIDE8PrvA0-unsplash.png`,
    alt: 'photographer: Loan',
  },
    {
    uid: 30,
    breed: 'turkish-van',
    animal: 'cat',
    image: require('@/assets/images/animals/luiza-sayfullina-9giow4jXrzM-unsplash.png'),
    url: `${IMAGE_BASE_URL}/luiza-sayfullina-9giow4jXrzM-unsplash.png`,
    alt: 'photographer: Luiza Sayfullina',
  },
  {
    uid: 31,
    breed: 'rex',
    animal: 'cat',
    image: require('@/assets/images/animals/manja-vitolic-gKXKBY-C-Dk-unsplash.png'),
    url: `${IMAGE_BASE_URL}/manja-vitolic-gKXKBY-C-Dk-unsplash.png`,
    alt: 'photographer: Manja Vitolic',
  },
   {
    uid: 32,
    breed: 'burmese',
    animal: 'cat',
    image: require('@/assets/images/animals/mikhail-vasilyev-IFxjDdqK_0U-unsplash.png'),
    url: `${IMAGE_BASE_URL}/mikhail-vasilyev-IFxjDdqK_0U-unsplash.png`,
    alt: 'photographer: Mikhail Vasilyev',
  },
     {
    uid: 33,
    breed: 'russian-blue',
    animal: 'cat',
    image: require('@/assets/images/animals/milada-vigerova-7E9qvMOsZEM-unsplash.png'),
    url: `${IMAGE_BASE_URL}/milada-vigerova-7E9qvMOsZEM-unsplash.png`,
    alt: 'photographer: Milada Vigerova',
  },
       {
    uid: 34,
    breed: 'ragdoll',
    animal: 'cat',
    image: require('@/assets/images/animals/nadi-whatisdelirium-fZ8uf_L52wg-unsplash.png'),
    url: `${IMAGE_BASE_URL}/nadi-whatisdelirium-fZ8uf_L52wg-unsplash.png`,
    alt: 'photographer: Nadi Whatisdelirium',
  },
         {
    uid: 35,
    breed: 'orange-cat',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-aleksandar-cvetanovic-605352-1560424.png'),
    url: `${IMAGE_BASE_URL}/pexels-aleksandar-cvetanovic-605352-1560424.png`,
    alt: 'photographer: Aleksandar Cvetanovic',
  },
           {
    uid: 36,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-bimarolla-3030635.png'),
    url: `${IMAGE_BASE_URL}/pexels-bimarolla-3030635.png`,
    alt: 'photographer: Bima Rolla',
  },
             {
    uid: 37,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-chevonrossouw-2558605.png'),
    url: `${IMAGE_BASE_URL}/pexels-chevonrossouw-2558605.png`,
    alt: 'photographer: Chevon Rossouw',
  },
                {
    uid: 38,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-fox-58267-755834.png'),
    url: `${IMAGE_BASE_URL}/pexels-fox-58267-755834.png`,
    alt: 'photographer: Fox',
  },
     {
    uid: 39,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-mai-ph-ng-uyen-30981175-29291018.png'),
    url: `${IMAGE_BASE_URL}/pexels-mai-ph-ng-uyen-30981175-29291018.png`,
    alt: 'photographer: Mai Ph Nguyen',
  },
  {
    uid: 40,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-pixabay-208984.png'),
    url: `${IMAGE_BASE_URL}/pexels-pixabay-208984.png`,
    alt: 'photographer: Pixabay',
  },
  {
    uid: 41,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-pixabay-416195.png'),
    url: `${IMAGE_BASE_URL}/pexels-pixabay-416195.png`,
    alt: 'photographer: pixabay',
  },
  {
    uid: 42,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/pexels-the-iop-86002042-34193811.png'),
    url: `${IMAGE_BASE_URL}/pexels-the-iop-86002042-34193811.png`,
    alt: 'photographer: The IOP',
  },
  {
    uid: 43,
    breed: 'chausie',
    animal: 'cat',
    image: require('@/assets/images/animals/timo-volz-ZlFKIG6dApg-unsplash.png'),
    url: `${IMAGE_BASE_URL}/timo-volz-ZlFKIG6dApg-unsplash.png`,
    alt: 'photographer: Timo Volz',
  },
  {
    uid: 44,
    breed: 'american-shorthair',
    animal: 'cat',
    image: require('@/assets/images/animals/zhang-kaiyv-b1-JDjIq_00-unsplash.png'),
    url: `${IMAGE_BASE_URL}/zhang-kaiyv-b1-JDjIq_00-unsplash.png`,
    alt: 'photographer: Zhang Kaiyv',
  },
];

export function getAnimalByUid(uid: number): Animal | undefined {
  return animals.find((animal) => animal.uid === uid);
}

// Get all unique animal types from the data
export function getAnimalTypes(): string[] {
  return [...new Set(animals.map((animal) => animal.animal))];
}
